# Generated by Django 4.2.5 on 2023-09-08 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_comment_name_comment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='employee',
        ),
    ]
