# Generated by Django 4.2.5 on 2023-09-08 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_user_comment_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='employee',
        ),
    ]
