# Generated by Django 4.2.5 on 2023-09-08 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_comment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='employee',
        ),
    ]
