# Generated by Django 4.2.5 on 2023-09-08 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_user_comment_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='employee',
            new_name='User',
        ),
    ]
